{
 "title": "octo2influx Energy Usage",
 "time": { "from": "now-7d", "to": "now-18h" },
 "templating": {
  "list": [
   { "name": "HistoryDuration", "label": "History Duration", "query": "7d,14d,30d,90d,180d,365d" },
   { "name": "bucket", "query": "octo2influx/autogen" },
   { "name": "usage_measurement", "query": "octopus-usage" },
   { "name": "tariffs_measurement", "query": "octopus-tariffs" },
   {
    "name": "electricity_import_tariff",
    "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${tariffs_measurement}\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> keep(columns: [\"tariff_code\", \"display_name\", \"_value\"])\n  |> first()\n  |> map(fn: (r) => ({display_value: \"${r.display_name}#@#${r.tariff_code}\"}))"
   },
   {
    "name": "electricity_export_tariff",
    "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${tariffs_measurement}\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> filter(fn: (r) => r[\"direction\"] == \"export\")\n  |> keep(columns: [\"tariff_code\", \"display_name\", \"_value\"])\n  |> first()\n  |> map(fn: (r) => ({display_value: \"${r.display_name}#@#${r.tariff_code}\"}))"
   },
   {
    "name": "gas_tariff",
    "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${tariffs_measurement}\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"gas\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> keep(columns: [\"tariff_code\", \"display_name\", \"_value\"])\n  |> first()\n  |> map(fn: (r) => ({display_value: \"${r.display_name}#@#${r.tariff_code}\"}))"
   }
  ]
 },
 "panels": [
  { "title": "Electrictity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Electricity Imported",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sum()\n",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Import/Export",
   "type": "timeseries",
   "description": "Time shown is the **end** of each half hour",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "import \"date\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: date.sub(d: 25h, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"export\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\n  |> fill(usePrevious: true)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_time: \"_stop\", _value: \"export_kWh\"})\n  |> group()\n",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "import \"date\"\n\nfrom(bucket:\"$bucket\")\n|> range(start: date.sub(d: 25h, from: v.timeRangeStart), stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"${tariffs_measurement}\")\n|> filter(fn: (r) => r.price_type == \"standard-unit-rates\")\n|> filter(fn: (r) => r.tariff_code == \"${electricity_export_tariff}\")\n|> filter(fn: (r) => r[\"direction\"] == \"export\")\n|> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n|> filter(fn: (r) => r._field == \"p/kWh_inc_vat\")\n|> map(fn: (r) => ({ r with \"export-unit-rates_£/kWh\": r._value / 100.0}))\n|> keep(columns: [\"_time\", \"export-unit-rates_£/kWh\"])\n\n\n  "
    },
    {
     "query": "import \"date\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: date.sub(d: 25h, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\n  |> fill(usePrevious: true)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_time: \"_stop\", _value: \"import_kWh\"})\n  |> group()"
    },
    {
     "query": "import \"date\"\nfrom(bucket:\"$bucket\")\n|> range(start: date.sub(d: 25h, from: v.timeRangeStart), stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"${tariffs_measurement}\")\n|> filter(fn: (r) => r.price_type == \"standard-unit-rates\")\n|> filter(fn: (r) => r.tariff_code == \"${electricity_import_tariff}\")\n|> filter(fn: (r) => r[\"direction\"] == \"import\")\n|> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n|> filter(fn: (r) => r._field == \"p/kWh_inc_vat\")\n|> map(fn: (r) => ({ r with \"import-unit-rates_£/kWh\": r._value / 100.0}))\n|> keep(columns: [\"_time\", \"import-unit-rates_£/kWh\"])\n\n"
    }
   ]
  },
  {
   "title": "Electricity Exported",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"export\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sum()\n",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Import Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "import \"date\"\n\nconsumption =\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_time: \"_stop\", _value: \"consumption_kWh\"})\n  |> group()\n\ncombinedRates = \nfrom(bucket:\"$bucket\")\n  |> range(start: date.sub(d: 25h, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${tariffs_measurement}\")\n  |> filter(fn: (r) => r.tariff_code == \"${electricity_import_tariff}\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> filter(fn: (r) => r._field =~ /_inc_vat$/)\n  |> aggregateWindow(every: 30m, fn: last, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") \n  |> rename(columns: {_time: \"_stop\"})\n\n\njoined = join(\n    tables: {consumption:consumption, combinedRates:combinedRates},\n    on: [\"_stop\"]\n  )\n  |> rename(columns: {_stop: \"_time\"})\n  \nstanding_cost = joined\n  // 48 increments of 30min in a day, then divide by 100 to go from pence to £\n  |> map(fn: (r) => ({ _time: r._time, _value: r[\"p/day_inc_vat\"]/48.0/100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Standing charge cost\"})\n\nusage_cost = joined\n  |> map(fn: (r) => ({ _time: r._time, _value: r.consumption_kWh * r[\"p/kWh_inc_vat\"] / 100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Usage cost\"})\n\ntotal_cost = joined\n  |> map(fn: (r) => ({ _time: r._time, _value: r[\"p/day_inc_vat\"]/48.0/100.0 + r.consumption_kWh * r[\"p/kWh_inc_vat\"] / 100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Total cost\"})\n\nunion(tables: [standing_cost, usage_cost, total_cost])",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Export Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "import \"date\"\n\nconsumption =\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"export\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_time: \"_stop\", _value: \"consumption_kWh\"})\n  |> group()\n\ncombinedRates = \nfrom(bucket:\"$bucket\")\n  |> range(start: date.sub(d: 25h, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${tariffs_measurement}\")\n  |> filter(fn: (r) => r.tariff_code == \"${electricity_export_tariff}\")\n  |> filter(fn: (r) => r[\"direction\"] == \"export\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> filter(fn: (r) => r._field =~ /_inc_vat$/)\n  |> aggregateWindow(every: 30m, fn: last, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") \n  |> rename(columns: {_time: \"_stop\"})\n\njoined = join(\n    tables: {consumption:consumption, combinedRates:combinedRates},\n    on: [\"_stop\"]\n  )\n  |> rename(columns: {_stop: \"_time\"})\n  \nstanding_cost = joined\n  // 48 increments of 30min in a day, then divide by 100 to go from pence to £\n  |> map(fn: (r) => ({ _time: r._time, _value: r[\"p/day_inc_vat\"]/48.0/100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Standing charge cost\"})\n\nexport_revenue = joined\n  |> map(fn: (r) => ({ _time: r._time, _value: r.consumption_kWh * r[\"p/kWh_inc_vat\"] / 100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Export revenue\"})\n\ntotal_revenue = joined\n  |> map(fn: (r) => ({ _time: r._time, _value: r[\"p/day_inc_vat\"]/48.0/100.0 + r.consumption_kWh * r[\"p/kWh_inc_vat\"] / 100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Total revenue\"})\n\nunion(tables: [standing_cost, export_revenue, total_revenue])",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Electricity History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Electricity Import",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sum()\n",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Import/Export per Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/London\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"export\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 1d, fn: sum)\n  |> timeShift(duration: -1m)\n  |> truncateTimeColumn(unit: 1d)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"export\"})\n"
    },
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/London\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 1d, fn: sum)\n  |> timeShift(duration: -1m)\n  |> truncateTimeColumn(unit: 1d)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"import\"})\n\n",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Export",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"export\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sum()\n",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Import Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "import \"date\"\n\nconsumption =\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_time: \"_stop\", _value: \"consumption_kWh\"})\n  |> group()\n\ncombinedRates = \nfrom(bucket:\"$bucket\")\n  |> range(start: date.sub(d: 25h, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${tariffs_measurement}\")\n  |> filter(fn: (r) => r.tariff_code == \"${electricity_import_tariff}\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> filter(fn: (r) => r._field =~ /_inc_vat$/)\n  |> aggregateWindow(every: 30m, fn: last, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") \n  |> rename(columns: {_time: \"_stop\"})\n\n\njoined = join(\n    tables: {consumption:consumption, combinedRates:combinedRates},\n    on: [\"_stop\"]\n  )\n  |> rename(columns: {_stop: \"_time\"})\n  \nstanding_cost = joined\n  // 48 increments of 30min in a day, then divide by 100 to go from pence to £\n  |> map(fn: (r) => ({ _time: r._time, _value: r[\"p/day_inc_vat\"]/48.0/100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Standing charge cost\"})\n\nusage_cost = joined\n  |> map(fn: (r) => ({ _time: r._time, _value: r.consumption_kWh * r[\"p/kWh_inc_vat\"] / 100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Usage cost\"})\n\ntotal_cost = joined\n  |> map(fn: (r) => ({ _time: r._time, _value: r[\"p/day_inc_vat\"]/48.0/100.0 + r.consumption_kWh * r[\"p/kWh_inc_vat\"] / 100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Total cost\"})\n\nunion(tables: [standing_cost, usage_cost, total_cost])",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Import Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "import \"date\"\n\nconsumption =\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_time: \"_stop\", _value: \"consumption_kWh\"})\n  |> group()\n\ncombinedRates = \nfrom(bucket:\"$bucket\")\n  |> range(start: date.sub(d: 25h, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${tariffs_measurement}\")\n  |> filter(fn: (r) => r.tariff_code == \"${electricity_import_tariff}\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"electricity\")\n  |> filter(fn: (r) => r._field =~ /_inc_vat$/)\n  |> aggregateWindow(every: 30m, fn: last, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") \n  |> rename(columns: {_time: \"_stop\"})\n\n\njoined = join(\n    tables: {consumption:consumption, combinedRates:combinedRates},\n    on: [\"_stop\"]\n  )\n  |> rename(columns: {_stop: \"_time\"})\n  \nstanding_cost = joined\n  // 48 increments of 30min in a day, then divide by 100 to go from pence to £\n  |> map(fn: (r) => ({ _time: r._time, _value: r[\"p/day_inc_vat\"]/48.0/100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Standing charge cost\"})\n\nusage_cost = joined\n  |> map(fn: (r) => ({ _time: r._time, _value: r.consumption_kWh * r[\"p/kWh_inc_vat\"] / 100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Usage cost\"})\n\ntotal_cost = joined\n  |> map(fn: (r) => ({ _time: r._time, _value: r[\"p/day_inc_vat\"]/48.0/100.0 + r.consumption_kWh * r[\"p/kWh_inc_vat\"] / 100.0}))\n  |> sum()\n  |> rename(columns: {\"_value\": \"Total cost\"})\n\nunion(tables: [standing_cost, usage_cost, total_cost])",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Gas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Gas Import",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"m3\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"gas\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sum()\n",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas Import per Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${usage_measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"m3\")\n  |> filter(fn: (r) => r[\"direction\"] == \"import\")\n  |> filter(fn: (r) => r[\"energy_type\"] == \"gas\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 1d, fn: sum)\n  |> timeShift(duration: -1m)\n  |> truncateTimeColumn(unit: 1d)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"import\"})",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}