name: Python Docker Build and Push
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR and push image
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extract short commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Push Docker image
        run: docker buildx build --file ./src/Dockerfile --platform linux/amd64 --push -t ghcr.io/echoblag/octo2influx${{ env.COMMIT_HASH }}



